"""create p1 core tables

Revision ID: 202606090001
Revises:
Create Date: 2026-06-09
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

revision = "202606090001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "sources",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("source_id", sa.String(length=64), nullable=False, unique=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("fetch_method", sa.String(length=64), nullable=False),
        sa.Column("url", sa.Text()),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("discovery_weight", sa.Float(), nullable=False),
        sa.Column("heat_signal_weight", sa.Float(), nullable=False),
        sa.Column("impact_signal_weight", sa.Float(), nullable=False),
        sa.Column("language", sa.String(length=32)),
        sa.Column("category_hint", sa.String(length=128)),
        sa.Column("fetch_interval", sa.String(length=64)),
        sa.Column("capabilities", sa.JSON()),
        sa.Column("last_fetched_at", sa.DateTime(timezone=True)),
        sa.Column("last_status", sa.String(length=64)),
        sa.Column("failure_reason", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table(
        "pipeline_runs",
        sa.Column("pipeline_run_id", sa.String(length=64), primary_key=True),
        sa.Column("run_type", sa.String(length=64), nullable=False),
        sa.Column("triggered_by", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("finished_at", sa.DateTime(timezone=True)),
        sa.Column("source_count", sa.Integer(), nullable=False),
        sa.Column("evidence_card_count", sa.Integer(), nullable=False),
        sa.Column("event_cluster_count", sa.Integer(), nullable=False),
        sa.Column("content_artifact_count", sa.Integer(), nullable=False),
        sa.Column("published_event_count", sa.Integer(), nullable=False),
        sa.Column("failed_step", sa.String(length=128)),
        sa.Column("error_summary", sa.Text()),
        sa.Column("model_usage", sa.JSON()),
        sa.Column("config_version", sa.String(length=64)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table(
        "evidence_cards",
        sa.Column("evidence_card_id", sa.String(length=64), primary_key=True),
        sa.Column("pipeline_run_id", sa.String(length=64), sa.ForeignKey("pipeline_runs.pipeline_run_id"), nullable=False),
        sa.Column("source_id", sa.String(length=64), sa.ForeignKey("sources.source_id"), nullable=False),
        sa.Column("source_item_id", sa.String(length=128), nullable=False),
        sa.Column("item_type", sa.String(length=64), nullable=False),
        sa.Column("original_title", sa.Text(), nullable=False),
        sa.Column("original_url", sa.Text()),
        sa.Column("canonical_url", sa.Text()),
        sa.Column("author", sa.String(length=255)),
        sa.Column("published_at", sa.DateTime(timezone=True)),
        sa.Column("discovered_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("raw_summary", sa.Text()),
        sa.Column("raw_excerpt", sa.Text()),
        sa.Column("raw_heat_metrics", sa.JSON()),
        sa.Column("raw_metadata", sa.JSON()),
        sa.Column("page_title", sa.Text()),
        sa.Column("page_excerpt", sa.Text()),
        sa.Column("page_text_hash", sa.String(length=128)),
        sa.Column("page_cache_path", sa.Text()),
        sa.Column("page_fetch_status", sa.String(length=64)),
        sa.Column("claim_summary", sa.Text()),
        sa.Column("normalized_title", sa.Text()),
        sa.Column("subjects", sa.JSON()),
        sa.Column("event_trigger", sa.Text()),
        sa.Column("event_type", sa.String(length=128)),
        sa.Column("category", sa.String(length=128)),
        sa.Column("heat_clues", sa.JSON()),
        sa.Column("impact_clues", sa.JSON()),
        sa.Column("audience_value_reason", sa.Text()),
        sa.Column("suggested_route", sa.String(length=128)),
        sa.Column("candidate_score", sa.Float(), nullable=False),
        sa.Column("candidate_reason", sa.Text()),
        sa.Column("merge_key_hint", sa.Text()),
        sa.Column("dedupe_key", sa.String(length=255)),
        sa.Column("content_hash", sa.String(length=128)),
        sa.Column("url_hash", sa.String(length=128)),
        sa.Column("model_name", sa.String(length=128)),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("card_version", sa.String(length=64), nullable=False),
        sa.Column("processing_status", sa.String(length=64), nullable=False),
        sa.Column("discard_reason", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.UniqueConstraint("source_id", "source_item_id", "prompt_version", name="uq_evidence_source_item_prompt"),
    )
    op.create_table(
        "event_clusters",
        sa.Column("event_cluster_id", sa.String(length=64), primary_key=True),
        sa.Column("event_key", sa.String(length=255), nullable=False),
        sa.Column("created_pipeline_run_id", sa.String(length=64), sa.ForeignKey("pipeline_runs.pipeline_run_id"), nullable=False),
        sa.Column("last_seen_pipeline_run_id", sa.String(length=64), sa.ForeignKey("pipeline_runs.pipeline_run_id")),
        sa.Column("title_hint", sa.Text(), nullable=False),
        sa.Column("summary_hint", sa.Text()),
        sa.Column("primary_subject", sa.String(length=255)),
        sa.Column("subjects", sa.JSON()),
        sa.Column("event_trigger", sa.Text()),
        sa.Column("event_type", sa.String(length=128)),
        sa.Column("category", sa.String(length=128)),
        sa.Column("merge_key", sa.Text()),
        sa.Column("heat_score", sa.Float(), nullable=False),
        sa.Column("impact_score", sa.Float(), nullable=False),
        sa.Column("audience_value_score", sa.Float(), nullable=False),
        sa.Column("ranking_score", sa.Float(), nullable=False),
        sa.Column("ranking_reason", sa.Text()),
        sa.Column("evidence_card_count", sa.Integer(), nullable=False),
        sa.Column("source_count", sa.Integer(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("event_time_hint", sa.Text()),
        sa.Column("cluster_status", sa.String(length=64), nullable=False),
        sa.Column("publish_decision", sa.String(length=64), nullable=False),
        sa.Column("brief_candidate", sa.Boolean(), nullable=False),
        sa.Column("planning_reason", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.UniqueConstraint("event_key", name="uq_event_clusters_event_key"),
    )
    op.create_table(
        "event_cluster_cards",
        sa.Column("event_cluster_card_id", sa.String(length=64), primary_key=True),
        sa.Column("event_cluster_id", sa.String(length=64), sa.ForeignKey("event_clusters.event_cluster_id"), nullable=False),
        sa.Column("evidence_card_id", sa.String(length=64), sa.ForeignKey("evidence_cards.evidence_card_id"), nullable=False),
        sa.Column("signal_role", sa.String(length=64), nullable=False),
        sa.Column("merge_reason", sa.Text()),
        sa.Column("added_by", sa.String(length=64), nullable=False),
        sa.Column("added_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.UniqueConstraint("event_cluster_id", "evidence_card_id", name="uq_cluster_evidence_card"),
    )
    op.create_table(
        "content_artifacts",
        sa.Column("content_artifact_id", sa.String(length=64), primary_key=True),
        sa.Column("event_cluster_id", sa.String(length=64), sa.ForeignKey("event_clusters.event_cluster_id"), nullable=False),
        sa.Column("pipeline_run_id", sa.String(length=64), sa.ForeignKey("pipeline_runs.pipeline_run_id"), nullable=False),
        sa.Column("artifact_type", sa.String(length=64), nullable=False),
        sa.Column("content_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("subtitle", sa.Text()),
        sa.Column("summary", sa.Text()),
        sa.Column("body", sa.Text()),
        sa.Column("body_format", sa.String(length=64), nullable=False),
        sa.Column("cover_image_url", sa.Text()),
        sa.Column("evidence_card_ids", sa.JSON()),
        sa.Column("source_refs", sa.JSON()),
        sa.Column("generation_reason", sa.Text()),
        sa.Column("model_name", sa.String(length=128)),
        sa.Column("prompt_version", sa.String(length=64)),
        sa.Column("generation_params", sa.JSON()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table(
        "quality_gate_results",
        sa.Column("quality_gate_result_id", sa.String(length=64), primary_key=True),
        sa.Column("content_artifact_id", sa.String(length=64), sa.ForeignKey("content_artifacts.content_artifact_id"), nullable=False),
        sa.Column("event_cluster_id", sa.String(length=64), sa.ForeignKey("event_clusters.event_cluster_id"), nullable=False),
        sa.Column("pipeline_run_id", sa.String(length=64), sa.ForeignKey("pipeline_runs.pipeline_run_id"), nullable=False),
        sa.Column("gate_version", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("check_results", sa.JSON()),
        sa.Column("fail_reasons", sa.JSON()),
        sa.Column("warning_messages", sa.JSON()),
        sa.Column("recommended_action", sa.String(length=64), nullable=False),
        sa.Column("checked_by", sa.String(length=64), nullable=False),
        sa.Column("model_name", sa.String(length=128)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table(
        "published_events",
        sa.Column("published_event_id", sa.String(length=64), primary_key=True),
        sa.Column("event_cluster_id", sa.String(length=64), sa.ForeignKey("event_clusters.event_cluster_id"), nullable=False),
        sa.Column("card_artifact_id", sa.String(length=64), sa.ForeignKey("content_artifacts.content_artifact_id"), nullable=False),
        sa.Column("detail_artifact_id", sa.String(length=64), sa.ForeignKey("content_artifacts.content_artifact_id"), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("display_title", sa.Text(), nullable=False),
        sa.Column("display_summary", sa.Text()),
        sa.Column("cover_image_url", sa.Text()),
        sa.Column("category", sa.String(length=128)),
        sa.Column("publish_status", sa.String(length=64), nullable=False),
        sa.Column("visibility", sa.String(length=64), nullable=False),
        sa.Column("published_by", sa.String(length=64), nullable=False),
        sa.Column("first_published_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("last_published_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("homepage_rank", sa.Integer()),
        sa.Column("ranking_score", sa.Float(), nullable=False),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("last_ranked_at", sa.DateTime(timezone=True)),
        sa.Column("admin_note", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.UniqueConstraint("event_cluster_id", name="uq_published_event_cluster"),
        sa.UniqueConstraint("slug", name="uq_published_events_slug"),
    )
    op.create_table(
        "briefs",
        sa.Column("brief_id", sa.String(length=64), primary_key=True),
        sa.Column("brief_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("overview", sa.Text()),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("item_count", sa.Integer(), nullable=False),
        sa.Column("pipeline_run_id", sa.String(length=64), sa.ForeignKey("pipeline_runs.pipeline_run_id"), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.UniqueConstraint("brief_date", "version", name="uq_briefs_date_version"),
    )
    op.create_table(
        "brief_items",
        sa.Column("brief_item_id", sa.String(length=64), primary_key=True),
        sa.Column("brief_id", sa.String(length=64), sa.ForeignKey("briefs.brief_id"), nullable=False),
        sa.Column("published_event_id", sa.String(length=64), sa.ForeignKey("published_events.published_event_id"), nullable=False),
        sa.Column("brief_artifact_id", sa.String(length=64), sa.ForeignKey("content_artifacts.content_artifact_id"), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("section", sa.String(length=128)),
        sa.Column("highlight_reason", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.UniqueConstraint("brief_id", "published_event_id", name="uq_brief_published_event"),
    )
    op.create_table(
        "admin_actions",
        sa.Column("admin_action_id", sa.String(length=64), primary_key=True),
        sa.Column("operator", sa.String(length=128), nullable=False),
        sa.Column("action_type", sa.String(length=128), nullable=False),
        sa.Column("target_type", sa.String(length=128), nullable=False),
        sa.Column("target_id", sa.String(length=128), nullable=False),
        sa.Column("reason", sa.Text()),
        sa.Column("before_snapshot", sa.JSON()),
        sa.Column("after_snapshot", sa.JSON()),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("error_message", sa.Text()),
        sa.Column("related_job_id", sa.String(length=128)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )


def downgrade() -> None:
    for table_name in [
        "admin_actions",
        "brief_items",
        "briefs",
        "published_events",
        "quality_gate_results",
        "content_artifacts",
        "event_cluster_cards",
        "event_clusters",
        "evidence_cards",
        "pipeline_runs",
        "sources",
    ]:
        op.drop_table(table_name)
